#!/bin/bash

echo "📦 Ajout de CollocatorDashboardView.swift au projet Xcode"
echo ""
echo "⚠️  Ce fichier doit être ajouté manuellement dans Xcode :"
echo ""
echo "1. Ouvrez Xcode"
echo "2. Dans le Project Navigator (à gauche), faites un clic droit sur le dossier 'Views/Screens'"
echo "3. Sélectionnez 'Add Files to DarnaApp...'"
echo "4. Naviguez vers :"
echo "   /Users/appleesprit/Documents/uyosra/DarnaFrontIOS-Gestion_User/DarnaApp/Views/Screens/CollocatorDashboardView.swift"
echo "5. Assurez-vous que :"
echo "   - 'Copy items if needed' est DÉCOCHÉ"
echo "   - 'Create groups' est sélectionné"
echo "   - La target 'DarnaApp' est COCHÉE"
echo "6. Cliquez sur 'Add'"
echo ""
echo "✅ Ensuite, nettoyez et rebuilder le projet :"
echo "   - Product > Clean Build Folder (Cmd+Shift+K)"
echo "   - Product > Build (Cmd+B)"
echo ""
echo "Le fichier est situé à :"
echo "/Users/appleesprit/Documents/uyosra/DarnaFrontIOS-Gestion_User/DarnaApp/Views/Screens/CollocatorDashboardView.swift"
